security:
    providers:
        user_db_provider:
            entity:
                class: App\Entity\User
                property: apiToken
        in_memory:
            memory:
                users:
                    admin:
                        password: $2y$12$LhoRWwnWimLqBjFeXOD59ObHQlALhaZh2pqkGzzTIrXeFZs/ltSju
                        roles: 'ROLE_ADMIN'
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN
        
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        
        api:
            pattern: ^/api/admin
            guard:
                authenticators:
                    - App\Security\TokenAuthenticator
            provider: user_db_provider
        main:
            anonymous: true
            provider: in_memory
            
    access_control:
        # - { path: ^/api/, roles: ROLE_API }
        - { path: ^/api/admin, roles: ROLE_ADMIN }
    encoders:
        Symfony\Component\Security\Core\User\User:
           algorithm: bcrypt
           cost: 12
